const Actions = {
  AC_SELECT_ITEM: "AC_SELECT_ITEM",
  AC_ADD_TASK: "AC_ADD_TASK",
  AC_UPDATE_TASK: "AC_UPDATE_TASK",
  AC_DELETE: "AC_DELETE",
  AC_ADD_LINK: "AC_ADD_LINK"
};
export default Actions;
